# Generated by Django 5.0.7 on 2024-07-20 13:10

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_alter_player_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='country',
            field=django_countries.fields.CountryField(default='Uz', max_length=2),
        ),
    ]
